services:
  - type: web
    name: dhanush-portfolio
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    publishDir: ./dist
    envVars:
      - key: NODE_ENV
        value: production
